all: assignment0_1 assignment0_2

assignment0_1: assignment0_1.c
	gcc -g -Wall -o assignment0_1 assignment0_1.c

assignment0_2: assignment0_2.c
	gcc -g -Wall -o assignment0_2 assignment0_2.c
clean:
	rm -f assignment0_1 assignment0_2
